### ISSUE TITLE
Use Extension in Docker

### ISSUE THREAD

**Issue by convivialapple** [FaustRen/bypass_recaptcha#1]
Thanks for sharing! Can I use it in docker environment with headless chrome-option?

**Comment by FaustRen** [comment]
Hi there! Yes, you can definitely use it in a Docker environment with a headless Chrome option. 

You just need to add the .crx extension file to your Docker container and configure Chrome options to load it.

Just a quick note: the .crx file wasn't created by me—I’ve confirmed it's safe through antivirus scans, but I’d recommend you scan it on your end as well before using it. 

I’m not responsible if anything unexpected happens with it 😄.

 Let me know if you need any setup help!

**Comment by FaustRen** [comment]
Hi @convivialapple  ,

As there has been no response, I am closing this issue. If you continue to experience the problem, please feel free to reopen the issue or create a new one.

Best,
Ren
